### ISSUE TITLE
It is recommended that the software can still run after being closed

### ISSUE THREAD

**Issue by wangzhenxing4** [oliver408i/mac-battery-controller#1]
When the software is closed, it should continue to run, not pause. Because, the software can not be a permanent program, but the reality is: the software will be shut down when the warning: All operations will be stopped

**Comment by oliver408i** [comment]
That is the point of closing the program: the user wants to stop it. If the user doesn't want to stop it, they keep it open in the background. If the app doesn't shut down all the active processes before it quits then there won't be a way for the user to control that action anymore without using something like the terminal to kill it
